//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.11
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. This configuration should not
 * be shared or posted to any public source code repository.
 */
public class AWSConfiguration {
    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub 76e7dd49-c176-4cdf-87a7-d8a1ab97589a aws-my-sample-app-android-v0.11";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
      Regions.fromName("us-east-1");
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "us-east-1:0227562f-8db5-4e75-a68f-2ec99330e9a3";
    // AMAZON MOBILE ANALYTICS
    public static final String  AMAZON_MOBILE_ANALYTICS_APP_ID =
        "44345a274a7e4576af88afb785523d16";
    // Amazon Mobile Analytics region
    public static final Regions AMAZON_MOBILE_ANALYTICS_REGION = Regions.US_EAST_1;
    public static final String AMAZON_CONTENT_DELIVERY_S3_BUCKET =
        "lifeline-contentdelivery-mobilehub-1183022899";
    public static final Regions AMAZON_CONTENT_DELIVERY_S3_REGION =
       Regions.fromName("us-west-2");
    // S3 BUCKET
    public static final String AMAZON_S3_USER_FILES_BUCKET =
        "lifeline-userfiles-mobilehub-1183022899";
    // S3 BUCKET REGION
    public static final Regions AMAZON_S3_USER_FILES_BUCKET_REGION =
        Regions.fromName("us-west-2");
    public static final Regions AMAZON_DYNAMODB_REGION =
       Regions.fromName("us-west-2");
    public static final String AMAZON_COGNITO_USER_POOL_ID =
        "us-east-1_NidzX21kM";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_ID =
        "2a8pufm48jafpv6nubb0b1sqno";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_SECRET =
        "sj9nglnpsjnip231l9ekpf7gde3h2o37e787mk2cbcu4fjv4f6f";
}
